### ISSUE TITLE
full db

### ISSUE THREAD

**Issue by depredadors** [NoffearrDeathProjecT/DeathCore_4.3.4#1]
I would like to try excellent job where I can download the database to beat the look greetings

**Comment by Noffearr** [comment]
Soon I'll post them wait!

**Comment by depredadors** [comment]
thank you very much be waiting for test your work

**Comment by shorden** [comment]
waiting ;|

**Comment by Noffearr** [comment]
Still post the databases design! Please testers so please report bugs and if possible help in correcting I'll be very grateful to it!

**Comment by shorden** [comment]
How long should we wait؟؟

**Comment by Noffearr** [comment]
Test Repack!

https://mega.co.nz/#!L09XVBCA!mnsb9rJ4wK4kZcV6ZRgroWPAjrGX_ZtWTqU0wD5oEAs
